cloud:
  aws:
    credentials:
      access-key: AKIAUYTB63BPDVV7K7MD
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

stripe:
  api:
    key: sk_test_51MTJ3WSGxlhGWErCSNOb0EsUx6t3bmKZBM6E35PFJx8VPdj3rfTthnb6ymURRgUchzdv7YTm7q0feSrbzDbV31Fc00ezeQQpou



application:
  bucket:
    name: redeyesncodemaster


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 50MB
      max-request-size: 45MB


