cloud:
  aws:
    credentials:
      access-key: AKIAUYTB63BPDVV7K7MD
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: redeyesncodemaster


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 50MB
      max-request-size: 45MB

server:
  port: 6767
